# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://yeqizhang.github.io
date_format: "ordinal"
title: 叶ღ
subtitle: "温不增华，寒不改叶"
description: "叶琦彰的个人博客"
keywords: 叶琦彰, Ye Qizhang, yeqizhang
timezone: Asia/Shanghai
encoding: "utf-8"
# sidebar-popular-repo.html 已将所有代码注释，不展示 my popular repository
side_bar_repo_limit: 0

# ---------------- #
#      Author      #
# ---------------- #
author: Ye Qizhang
# organization: zkh360.com
# organization_url: http://www.zkh360.com
github_username: yeqizhang
location: Guangzhou, China
email: yqz19920528@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
#匹配的链接
permalink: /:year/:month/:day/:title/
#gems: tgc注释掉——"gems" key is now named "plugins".
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: yeqizhang/yeqizhang.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: 
    repo: 
    oauth:
        client_id: 
        client_secret: 
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: yeqizhang
    repo: yeqizhang.github.io
    clientID: b090e8b09cca1ac1514c
    clientSecret: 3b91007a7ee8dfb42dd283712c607893fde31201
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
#google:
    #analytics_id: UA-80669434-1
